Merge Experiment/restructure to develop_v3
LORD-MicroStrain/mip_sdk pull request #110
Opened 2024-07-16 22:58 UTC by microstrain-sam

* Restructure into microstrain and mip libraries
* Split C and C++ sources
* Metadata

2024-08-19 17:31 UTC, dacuster commented
It might be worth updating the package contact info, it still says Parker (CMake)

2024-08-19 18:38 UTC, dacuster commented
Re-enable the Linux ARM builders in the Jenkinsfile

2024-08-20 15:37 UTC, dacuster commented
src/cpp/microstrain/
    extras/scope_helper.h/cpp - change namespace to microstrain (also closing bracket comment on the namespace)

src/c/microstrain/
    common/device_models.h/c - change namespace to microstrain (also closing bracket comment on the namespace)
    common/loggin.h - macros using MIP instead of MICROSTRAIN

2024-08-20 16:33 UTC, dacuster commented
Are we sticking with external includes wrapped in <> instead of ""? A few MicroStrain SDK include headers in the MIP SDK would need updating/ Also, a few places has system includes above MIP/MicroStrain includes. I'd say move those below our includes to prevent any issues

2024-08-21 13:21 UTC, dacuster commented
Not sure if this should be separate, but the licenses in the examples say HBK MICROSTRAIN instead of MICROSTRAIN BY HBK. We should update those

2024-08-21 13:35 UTC, dacuster requested changes
Going to work on integration with this to make sure it all works. Let me know when those additional bugs are fixed as well

2024-08-21 13:35 UTC, dacuster commented on cmake/check_metadata.cmake
> +check_cxx_source_compiles("
Change this to `CHECK_INCLUDE_FILE_CXX(span MIP_COMPILER_SUPPORTS_METADATA)`

Also would help to add this to make sure the values are bools
`
if(MIP_COMPILER_SUPPORTS_METADATA)
    set(MIP_COMPILER_SUPPORTS_METADATA TRUE)
elseif(NOT MIP_COMPILER_SUPPORTS_METADATA)
    set(MIP_COMPILER_SUPPORTS_METADATA FALSE)
endif()
`

2024-08-21 13:35 UTC, dacuster commented on CMakeLists.txt
> +#set(CMAKE_CXX_STANDARD 14)
Remove this if they're no longer needed

2024-08-21 13:35 UTC, dacuster commented on CMakeLists.txt
> +#if("cxx_std_20" IN_LIST CMAKE_CXX_COMPILE_FEATURES)
Remove this is no longer needed

2024-08-21 13:35 UTC, dacuster commented on CMakeLists.txt
>  find_package(Git)
Since there's a bit of restructure, it might make sense to fix the format of this Git block (4 spaces instead of 2)

Can't comment on the right line, but 95 has `if (...`

2024-08-21 13:35 UTC, dacuster commented on CMakeLists.txt
> +#include_directories(src/c)
Is this still needed?

2024-08-21 13:35 UTC, dacuster commented on CMakeLists.txt
> +    add_compile_definitions("NOMINMAX=1" "_WIN32_WINNT=0x0501")
It might make sense to just define this as `_WIN32_WINNT_WINXP` instead of `0x0501`

2024-08-21 13:35 UTC, dacuster commented on CMakeLists.txt
>  if(MSVC)
Fix the formatting here for consistency

2024-08-21 13:35 UTC, dacuster commented on CMakeLists.txt
> +## Only install headers that we build the source files for
Are we updating the packaging later or can this be removed?

2024-08-21 13:35 UTC, dacuster commented on README.md
> +applications may which to change this to `uint32_t` via the `MICROSTRAIN_TIMESTAMP_TYPE` define. Note that wraparound is
change which to wish

2024-08-21 13:35 UTC, dacuster commented on README.md
> +* A working C++ compiler, if using any C++ features.
For consistency, remove the period

2024-08-21 13:35 UTC, dacuster commented on README.md
> +  * C++20 or later for metadata and associated examples.
For consistency, remove the period

2024-08-21 13:35 UTC, dacuster commented on README.md
> +  * Define `MICROSTRAIN_ENABLE_CPP=OFF` if you don't want to use any C++. Note that some features are only available in C++.
For consistency, remove the period

2024-08-21 13:35 UTC, dacuster commented on README.md
> +[Enable it](#build-configuration) in the CMake configuration with `-DMICROSTRAIN_ENABLE_TCP=1`.
For consistency, remove the period

2024-08-21 13:35 UTC, dacuster commented on README.md
> +[Enable it](#build-configuration) in the CMake configuration with `-DMICROSTRAIN_ENABLE_SERIAL=1`.
For consistency, remove the period

2024-08-21 13:35 UTC, dacuster commented on README.md
> +* MICROSTRAIN_TIMESTAMP_TYPE - Overrides the default timestamp type. See the timestamps section in the documentation.
Adding a link to the timestamps section would be useful

2024-08-21 13:35 UTC, dacuster commented on README.md
>  The following options may be specified when configuring the build with CMake (e.g. `cmake .. -DOPTION=VALUE`):
Take a look at the MSCL readme in the BuildScripts directory for a nice way to lay these out into a table. Maybe for a later update though

2024-08-21 13:35 UTC, dacuster commented on README.md
Can't comment on the line, but the Minimum required files section needs updates on the directories. Not sure the best approach since there's `src/c/mip/definitions` and `src/cpp/mip/definitions`

2024-08-21 13:35 UTC, dacuster commented on test/CMakeLists.txt
> +#if(MICROSTRAIN_ENABLE_SERIAL)
Is there an issue including this or can it be removed?

2024-08-21 13:35 UTC, dacuster commented on src/c/microstrain/common/CMakeLists.txt
> +
Remove the extra empty line

2024-08-21 13:35 UTC, dacuster commented on src/c/microstrain/common/CMakeLists.txt
> +set(SOURCES
We should look into sorting these into their respective 'groups' for Visual Studio users.
`source_group`

2024-08-21 13:35 UTC, dacuster commented on src/c/microstrain/common/CMakeLists.txt
> +    target_sources(microstrain_common PRIVATE "../../../c/microstrain/common/logging.c")
Would it make sense to check for `MICROSTRAIN_ENABLE_LOGGING` before add_library and append this to `SOURCES`? Then keep this block here for the target-specific modifications? Also, we're already in the c/microstrain/common directory here, you can use `CMAKE_CURRENT_LIST_DIR`

2024-08-21 13:35 UTC, dacuster commented on src/c/microstrain/common/embedded_time.h
> +
Remove extra empty lines

2024-08-21 13:35 UTC, dacuster commented on src/c/microstrain/common/logging.h
> +#define MIP_LOG_INIT(callback, level, user) microstrain_logging_init(callback, level, user)
Change this to MICROSTRAIN_LOG_INIT

2024-08-21 13:35 UTC, dacuster commented on src/c/microstrain/common/logging.h
> +#define MIP_LOG_LOG(level, ...) microstrain_logging_log(level, __VA_ARGS__)
MICROSTRAIN_LOG_LOG

The rest of these macros need updating as well from `MIP` to `MICROSTRAIN`

2024-08-21 13:35 UTC, dacuster commented on src/c/microstrain/common/logging.c
>  ///       Call MIP_LOG_* macros instead of using this function directly
MIP_LOG_* -> MICROSTRAIN_LOG_*

2024-08-21 13:35 UTC, dacuster commented on src/c/microstrain/common/logging.h
>  ///@brief Helper macro used to initialize the MIP logger.
MicroStrain logger

2024-08-21 13:35 UTC, dacuster commented on src/c/microstrain/common/logging.h
>  ///@param level    The level that the MIP SDK should log at
MicroStrain SDK

2024-08-21 13:35 UTC, dacuster commented on src/c/microstrain/common/platform.h
> +#elif defined __linux__
We also have support for ARM, so it might make sense to add it under Linux

2024-08-21 13:35 UTC, dacuster commented on src/c/microstrain/common/serialization.h
> +//#include "mip/mip_field.h"
Are these still needed?

2024-08-21 13:35 UTC, dacuster commented on src/c/microstrain/common/serialization.h
> +#if 0
Is this temporary?

2024-08-21 13:35 UTC, dacuster commented on src/c/microstrain/connections/serial/CMakeLists.txt
> +add_library(microstrain_serial ${SOURCES})
Add files to source_group for Visual Studio users

2024-08-21 13:35 UTC, dacuster commented on src/c/microstrain/connections/serial/serial_port.c
Perfect opportunity for the platform.h macros

2024-08-21 13:35 UTC, dacuster commented on src/c/microstrain/connections/CMakeLists.txt
> +#option(MICROSTRAIN_ENABLE_SERIAL "Build serial connection support into the library and examples" ON)
Still needed?

2024-08-21 13:35 UTC, dacuster commented on src/c/mip/CMakeLists.txt
> +#option(MIP_ENABLE_DIAGNOSTICS "Enable various diagnostic counters in the mip library for debugging." OFF)
Still needed?

2024-08-21 13:35 UTC, dacuster commented on src/c/mip/mip_all.h
>  //MIP Utils
MicroStrain Utils

2024-08-21 13:35 UTC, dacuster commented on src/c/mip/mip_dispatch.h
> +typedef void (*mip_dispatch_packet_callback)(void *context, const mip_packet_view *packet, mip_timestamp timestamp);
Probably an IDE setting which did this, but move the * back on the type. Looks like most/all of this file was updated like that

2024-08-21 13:35 UTC, dacuster commented on src/c/mip/mip_dispatch.h
> +    void *_user_data;                                 ///<@private User-provided pointer which is passed directly to the callback.
Not aligned with the rest of the variables anymore

2024-08-21 13:35 UTC, dacuster commented on src/c/mip/mip_parser.c
MIPPARSER_RESET_LENGTH -> MIP_PARSER_RESET_LENGTH

2024-08-21 13:35 UTC, dacuster commented on src/c/mip/mip_serialization.c
> +///@brief Initializer a serialization struct for creation of a new field at the
Initializer -> Initialize

2024-08-21 13:35 UTC, dacuster commented on src/c/mip/mip_serialization.c
> +///@note Call microstrain_serializer_finiish_new_field after the data has been serialized.
finiish -> finish

2024-08-21 13:35 UTC, dacuster commented on src/c/mip/mip_serialization.c
Should this be moved to MicroStrain SDK? All the functions are microstrain instead of mip

2024-08-21 13:35 UTC, dacuster commented on src/c/mip/mip_serialization.h
> +} // namespace mip
I've noticed these are out of order from their declarations at the top of the file in most/all of our sources. We should update that at some point

2024-08-21 13:35 UTC, dacuster commented on src/cpp/microstrain/common/serialization/readwrite.hpp
> +typename std::enable_if<std::is_arithmetic<T>::value && sizeof(T) == 1, size_t>::type
You can simplify all of this with `typename std::enable_if_t<std::is_arithmetic_v<T> && sizeof(T) == 1, size_t>`

Same goes for the rest of this file

2024-08-21 13:35 UTC, dacuster commented on src/cpp/microstrain/common/serialization/serializer.hpp
> +
Cleanup these couple of extra empty lines

2024-08-21 13:35 UTC, dacuster commented on src/cpp/microstrain/common/serialization/serializer.hpp
> +typename std::enable_if<std::is_arithmetic<T>::value, size_t>::type
Same as mentioned in readwrite.cpp, this can be simplified

2024-08-21 13:35 UTC, dacuster commented on src/cpp/microstrain/common/platform.hpp
> +#   include <version>
I feel like the # should be with the directive not indented

2024-08-21 13:35 UTC, dacuster commented on src/cpp/microstrain/common/platform.hpp
Add a user option for the C/CXX standard defaulted to the latest. Fixes any issues with Endian and similar functionality. Also add `/Zc:__cplusplus` target_compile_option for MSVC to update __cplusplus to the right version being used

2024-08-21 13:35 UTC, dacuster commented on src/cpp/microstrain/common/serialization.hpp
> +namespace microstrain
Is anything going to be added here?

2024-08-21 13:35 UTC, dacuster commented on src/cpp/microstrain/connections/serial/serial_connection.cpp
>  ///@copydoc mip::Connection::recvFromDevice
microstrain::Connection

2024-08-21 13:35 UTC, dacuster commented on src/cpp/microstrain/connections/tcp/tcp_connection.cpp
>  ///@brief Creates a TcpConnection that will communicate with a device over TCP
param hostName -> hostname

2024-08-21 13:35 UTC, dacuster commented on src/cpp/microstrain/connections/tcp/tcp_connection.hpp
>      ~TcpConnection();
Specify `override` for these destructors

2024-08-21 13:35 UTC, dacuster commented on src/cpp/microstrain/connections/tcp/tcp_connection.hpp
> -    TcpConnection() = default;
Should these be marked deleted instead of not explicitly defining them or can we have connections without hostnames and ports?

2024-08-21 13:35 UTC, dacuster commented on src/cpp/microstrain/connections/tcp/tcp_connection.hpp
> +class TcpConnection : public microstrain::Connection
The class can be marked final instead of each member function

2024-08-21 13:35 UTC, dacuster commented on src/cpp/microstrain/connections/connection.hpp
> +#if __cpp_lib_span >= 202002L
I just realized, but shouldn't these checks be `#if __cplusplus >= __cpp_lib_span`? I think those macros are always going to equal those versions, but we need to check if `__cplusplus` is set to that version

2024-08-21 13:35 UTC, dacuster commented on src/cpp/microstrain/extras/scope_helper.cpp
Update the namespace to microstrain

2024-08-21 13:35 UTC, dacuster commented on src/cpp/microstrain/extras/scope_helper.hpp
Update the namespace to microstrain

2024-08-21 13:35 UTC, dacuster commented on src/cpp/mip/definitions/common.hpp
> +    ///// Pack vector into a raw byte buffer.
Can we remove this?

2024-08-21 13:35 UTC, dacuster commented on src/cpp/mip/definitions/common.hpp
> +///@}
Can we remove this?

2024-08-21 13:35 UTC, dacuster commented on src/cpp/mip/mip.hpp
Is this just a wrapper to include mip_interface?

2024-08-21 13:35 UTC, dacuster commented on src/cpp/mip/mip_descriptors.hpp
> +///@}
Can this be removed?

2024-08-21 13:35 UTC, dacuster commented on src/cpp/mip/mip_field.hpp
> +///@}
Can this be removed?

2024-08-21 13:35 UTC, dacuster commented on src/cpp/mip/mip_interface.hpp
>  ///@tparam Send A compile-time pointer to the callback function.
Send -> Recv

2024-08-21 13:35 UTC, dacuster commented on src/cpp/mip/mip_interface.hpp
>  ///@tparam Send A compile-time pointer to the callback function.
Send -> Update

2024-08-21 13:35 UTC, dacuster commented on src/cpp/mip/mip_interface.hpp
>  ///@}
Can this be removed?

2024-08-21 13:35 UTC, dacuster commented on src/cpp/mip/mip_serialization.hpp
> +}
namespace serialization comment

2024-08-21 13:35 UTC, dacuster commented on examples/CMakeLists.txt
> +if(MICROSTRAIN_ENABLE_SERIAL OR MICROSTRAIN_ENABLE_TCP)
I'd add the MICROSTRAIN_ENABLE_CPP to this statement to reduce nesting

2024-08-21 13:35 UTC, dacuster commented on examples/CMakeLists.txt
I think it'd make things easier for each example to have its own CMakeLists.txt and add them through this file. It'd make things easier for customers to copy most things they needs for a standalone example. Overall, this rework is a lot better than what was there though

2024-08-21 18:27 UTC, microstrain-sam commented on examples/CMakeLists.txt
I agree, but that's outside the scope of this PR. I entered a ticket to track this idea.

2024-08-21 20:24 UTC, microstrain-sam commented on src/cpp/microstrain/common/serialization.hpp
> +namespace microstrain
Probably not. I'll remove the namespace.

2024-08-21 20:30 UTC, microstrain-sam commented on README.md
> +[Enable it](#build-configuration) in the CMake configuration with `-DMICROSTRAIN_ENABLE_SERIAL=1`.
This is a sentence so should have a period.

2024-08-21 20:52 UTC, microstrain-sam commented on src/c/microstrain/common/CMakeLists.txt
> +set(SOURCES
Created an issue.

2024-08-21 20:58 UTC, microstrain-sam commented on src/c/microstrain/common/platform.h
> +#elif defined __linux__
We don't need any architecture checks in here yet, but if/when we do we can add ARM.

2024-08-21 21:34 UTC, microstrain-sam commented on src/c/mip/mip_serialization.c
No, these are MIP-specific (notice the parameters are MIP types). Could be named mip_serializer_xxx, but this naming is in line with the rest of the microstrain_serializer_xxx functions. They operate on microstrain_serializer objects so I'd say this follows the convention.

2024-08-21 21:38 UTC, microstrain-sam commented on src/c/mip/mip_serialization.h
> +} // namespace mip
Not sure what you mean.

2024-08-21 21:43 UTC, microstrain-sam commented on src/cpp/microstrain/common/serialization/readwrite.hpp
> +typename std::enable_if<std::is_arithmetic<T>::value && sizeof(T) == 1, size_t>::type
`enable_if_t` is c++14

2024-08-21 21:51 UTC, microstrain-sam commented on src/cpp/microstrain/connections/tcp/tcp_connection.hpp
> +class TcpConnection : public microstrain::Connection
Changed to `override`

2024-08-21 21:52 UTC, microstrain-sam commented on src/cpp/microstrain/connections/tcp/tcp_connection.hpp
>      ~TcpConnection();
Not necessary since it's the destructor. It can't not override the base class.

2024-08-21 21:55 UTC, microstrain-sam commented on src/cpp/microstrain/connections/connection.hpp
> +#if __cpp_lib_span >= 202002L
Changed to MICROSTRAIN_HAS_SPAN from platform.hpp.

2024-08-21 21:58 UTC, microstrain-sam commented on src/cpp/mip/definitions/common.hpp
> +///@}
No, that's part of the doxygen group started at the top of the file.

2024-08-23 17:18 UTC, microstrain-sam commented on CMakeLists.txt
> +## Only install headers that we build the source files for
We'll update packaging & installation later.

2024-08-23 17:20 UTC, microstrain-sam commented on src/c/mip/mip_parser.c
This has been addressed in the new parser branch. Not updating here to avoid future merge conflict.

2024-09-09 18:32 UTC, dacuster approved these changes

2024-09-20 20:21 UTC, merged