Adds descriptor set as a parameter to the callback for registerDataCallback
LORD-MicroStrain/mip_sdk pull request #26
Opened 2022-09-20 16:27 UTC by robbiefish

**NOTE**: This is an interface breaking change

This is useful if (like in the ROS driver) you handle data fields in mostly the same way, but need to store them somewhere different, or do something slightly different based on the descriptor set. For example:

```C++
void MicrostrainPublishers::handleGnssPosLlh(const uint8_t descriptor_set, const mip::data_gnss::PosLlh& pos_llh, mip::Timestamp timestamp)
{
  // Find the right publisher based on the descriptor set
  const size_t index = (descriptor_set == mip::data_gnss::MIP_GNSS1_DATA_DESC_SET) ? 0 : 1;
  const auto& pub = gnss_publishers_[index];  // Vector with a publisher for each GNSS publisher
  
  // Fill out the message and publish (most of the work)
  ...
}
```

2022-09-20 17:02 UTC, microstrain-sam requested changes
Yes, I think this is a good idea. The same situation could apply to shared data quantities as well. 
The current workaround for your example would be to define two helper functions (lambdas?) or maybe one function templated on the descriptor set. Either of those gets ugly fast though if you have to do it a lot.

We should implement it in the C interface too (see mip_dispatch_field_callback).

Personally I'd prefer the descriptor set to come after the field in the parameter list since it's not as important as the field and won't be used every time.

If you're feeling ambitious, you could make an overload to registerDataCallback which doesn't require that parameter. Then it's not a breaking change (to the C++ api anyway, the C api would still have to change).

2022-09-20 18:17 UTC, robbiefish commented
So I swapped the parameter order, and added a new function instead of modifying the existing one. I tried to have one call the other, but ran into some problems with that, so just ended up copying and pasting the logic and modifying as needed

I don't understand how I would modify the C functions, as the problem with the C++ functions was that the function would receive the parsed field which did not have an accurate descriptor set. However, in C++ the field callback provides a `mip_field` object which can be used to find the descriptor set

2022-09-21 14:34 UTC, microstrain-sam commented
> So I swapped the parameter order, and added a new function instead of modifying the existing one. I tried to have one call the other, but ran into some problems with that, so just ended up copying and pasting the logic and modifying as needed

Yeah, I'm not sure it's possible to have one call the other because the functions have to be stateless... though in theory it's possible. It might need a third helper function to do it, a lambda can't be used as a template argument (until C++20 anyway).

> I don't understand how I would modify the C functions, as the problem with the C++ functions was that the function would receive the parsed field which did not have an accurate descriptor set. However, in C++ the field callback provides a `mip_field` object which can be used to find the descriptor set

Oh you're right, it's only the extracted data callback that has this issue. Disregard.

Can you add the member function version as well?

2022-09-21 14:52 UTC, robbiefish commented
Is [this](https://github.com/LORD-MicroStrain/mip_sdk/pull/26/files#diff-b49d9eae90358003b157638bfdb4daedef3ff3b9b59f90b79a180af03f76b61cR239) not the member function version?

2022-09-21 20:48 UTC, merged